project:
  type: website
  output-dir: docs 

website:
  title: "Daniel Vovk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Cushing Trading Strategy
      - href: https://dannyboy777257.shinyapps.io/refineryanalysis/
        text: USGC Refinery Analysis

format:
  html:
    theme:
      light: yeti
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

